@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.visualitycompat.particle.type;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;