@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.visualitycompat.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;