@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.visualitycompat.mixin;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;