@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.visualitycompat.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;